# Generated by Django 4.2.30 on 2026-06-07 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_category_options_alter_favorite_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='savedaddress',
            options={'ordering': ['-created_at'], 'verbose_name': 'Сохранённый способ получения', 'verbose_name_plural': 'Сохранённые способы получения'},
        ),
        migrations.AddField(
            model_name='savedaddress',
            name='order_type',
            field=models.CharField(choices=[('delivery', '🚚 Доставка'), ('pickup', '🏪 Самовывоз')], default='delivery', max_length=10),
        ),
        migrations.AlterField(
            model_name='savedaddress',
            name='address',
            field=models.TextField(blank=True, help_text='Адрес доставки (пусто для самовывоза)'),
        ),
        migrations.AlterField(
            model_name='savedaddress',
            name='label',
            field=models.CharField(blank=True, help_text='Метка: Дом, Работа, Самовывоз', max_length=50),
        ),
        migrations.AlterField(
            model_name='savedaddress',
            name='phone',
            field=models.CharField(blank=True, help_text='Телефон для этого способа', max_length=20),
        ),
    ]
