# Generated by Django 4.2.30 on 2026-06-07 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_alter_savedaddress_options_savedaddress_order_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('delivery', 'Доставка'), ('pickup', 'Самовывоз')], default='delivery', help_text='Доставка или самовывоз', max_length=10),
        ),
    ]
